### ISSUE TITLE
能提供那个1M的训练语料作为参考吗

### ISSUE THREAD

**Issue by SeekPoint** [hit-computer/char-rnn#5]

**Comment by hit-computer** [comment]
其实那个1M的语料很简单的。主要是为了用theano重现一下karpathy的模型，所以训练语料是随便选的，就是很多篇与“选择”相关的中学生语文作文。你想要的话，留个邮箱我发你吧。

**Comment by SeekPoint** [comment]
多谢，想直接重现一下
yk_data@126.com

**Comment by xunanzhang** [comment]
可否也将处理好的文本发我一份，看看处理后文本的格式，谢谢了 xunanzhang@foxmail.com

**Comment by hit-computer** [comment]
@xunanzhang 已发你邮箱咯 :)

**Comment by SeekPoint** [comment]
@hit-computer @xunanzhang 
please sent to me a copy ,thanks!
yk_data@126.com
